"""
Export utilities for TravelX AI
Supports PDF, JSON, and iCalendar exports
"""
from datetime import datetime, timedelta
import json
import re

def clean_html(text):
    """Remove HTML tags from text"""
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)

def export_to_json(trip_data):
    """Export trip data to JSON format"""
    export_data = {
        "trip_info": {
            "source": trip_data.get("source"),
            "destination": trip_data.get("destination"),
            "start_date": trip_data.get("start_date"),
            "end_date": trip_data.get("end_date"),
            "days": trip_data.get("days")
        },
        "itinerary": clean_html(trip_data.get("itinerary", "")),
        "weather": trip_data.get("weather_data"),
        "route": trip_data.get("route_data"),
        "exported_at": datetime.now().isoformat()
    }
    return json.dumps(export_data, indent=2)

def export_to_ical(trip_data):
    """Export trip to iCalendar format"""
    start_date = datetime.strptime(trip_data.get("start_date"), "%Y-%m-%d")
    end_date = datetime.strptime(trip_data.get("end_date"), "%Y-%m-%d")
    
    ical = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//TravelX AI//Trip Planner//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:TravelX AI Trip
X-WR-TIMEZONE:UTC

BEGIN:VEVENT
UID:{datetime.now().timestamp()}@travelx-ai.com
DTSTAMP:{datetime.now().strftime('%Y%m%dT%H%M%SZ')}
DTSTART;VALUE=DATE:{start_date.strftime('%Y%m%d')}
DTEND;VALUE=DATE:{(end_date + timedelta(days=1)).strftime('%Y%m%d')}
SUMMARY:Trip to {trip_data.get('destination')}
DESCRIPTION:{clean_html(trip_data.get('itinerary', ''))[:500]}...
LOCATION:{trip_data.get('destination')}
STATUS:CONFIRMED
SEQUENCE:0
END:VEVENT

END:VCALENDAR"""
    
    return ical

def export_to_markdown(trip_data):
    """Export trip to Markdown format"""
    md = f"""# Trip to {trip_data.get('destination')}

## Trip Details
- **From:** {trip_data.get('source')}
- **To:** {trip_data.get('destination')}
- **Start Date:** {trip_data.get('start_date')}
- **End Date:** {trip_data.get('end_date')}
- **Duration:** {trip_data.get('days')} days

## Itinerary

{clean_html(trip_data.get('itinerary', ''))}

"""
    
    # Add route info if available
    route_data = trip_data.get('route_data')
    if route_data:
        md += f"""## Route Information
- **Distance:** {route_data.get('distance_km')} km
- **Estimated Duration:** {route_data.get('duration_hr')} hours

"""
    
    # Add weather info if available
    weather_data = trip_data.get('weather_data')
    if weather_data and weather_data.get('days'):
        md += "## Weather Forecast\n\n"
        for day in weather_data['days'][:5]:
            md += f"- **{day.get('datetime')}:** {day.get('temp')}°C, {day.get('conditions')}\n"
    
    md += f"\n---\n*Generated by TravelX AI on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n"
    
    return md

def create_shareable_link(trip_id):
    """Create a shareable link for a trip"""
    # In a real application, this would generate a unique token
    return f"/share/{trip_id}"
